Project Name: "AI Interviewer"
Employee Name: "Lanka Yesesvini Sai"

models_used:
  - llama-3.1-8b-instant
  - meta-llama/llama-3.2-11b-vision-instruct
  - mistralai/Mistral-7B-Instruct-v0.2
  - all-MiniLM-L6-v2

data:
  - synthetic
  - user-provided-resume

tools:
  - langgraph
  - streamlit
  - chromadb
  - sentence-transformers
  - groq
  - openrouter
  - huggingface

evaluation:
  - automated
  - llm-based

compute:
  platform: cloud
  gpu: none
